on:
  issues:
    types: [opened]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save data
        run: |
          echo "${{ github.event.issue.body }}" > data.txt
          git add .
          git commit -m "Update data from issue #${{ github.event.issue.number }}"
          git push
      - name: Close issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.update({
              issue_number: context.issue.number,
              state: 'closed'
            })
